[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@aave/core-v3/contracts=lib/aave-v3-core/contracts",
    "@chainlink/contracts-ccip=lib/ccip/contracts",
    "@uniswap/v3-periphery=lib/v3-periphery",
    "@uniswap/v3-core=lib/v3-core",
    "@chainlink/contracts=lib/chainlink/contracts",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
